const stockData = [
  { symbol: "ADANIENT", pChange: 7 },
  { symbol: "ADANIPORTS", pChange: 3.5 },
  { symbol: "APOLLOHOSP", pChange: 6 },
  { symbol: "ASIANPAINT", pChange: 3 },
  { symbol: "AXISBANK", pChange: 3 },
  { symbol: "BAJAJ-AUTO", pChange: 10 },
  { symbol: "BAJAJFINSV", pChange: 2.5 },
  { symbol: "BAJFINANCE", pChange: 2.5 },
  { symbol: "BHARTIARTL", pChange: 2.5 },
  { symbol: "BPCL", pChange: 3 },
  { symbol: "BRITANNIA", pChange: 3.5 },
  { symbol: "CIPLA", pChange: 3 },
  { symbol: "COALINDIA", pChange: 2.5 },
  { symbol: "BEL", pChange: 2 },
  { symbol: "DRREDDY", pChange: 6.5 },
  { symbol: "EICHERMOT", pChange: 3.5 },
  { symbol: "GRASIM", pChange: 4 },
  { symbol: "HCLTECH", pChange: 2.5 },
  { symbol: "HDFCBANK", pChange: 4 },
  { symbol: "HDFCLIFE", pChange: 1.5 },
  { symbol: "HEROMOTOCO", pChange: 7 },
  { symbol: "HINDALCO", pChange: 2.5 },
  { symbol: "HINDUNILVR", pChange: 3.5 },
  { symbol: "ICICIBANK", pChange: 2.5 },
  { symbol: "INDUSINDBK", pChange: 3 },
  { symbol: "INFY", pChange: 3 },
  { symbol: "ITC", pChange: 3 },
  { symbol: "JSWSTEEL", pChange: 2 },
  { symbol: "KOTAKBANK", pChange: 2.5 },
  { symbol: "LT", pChange: 4.5 },
  { symbol: "TRENT", pChange: 7.5 },
  { symbol: "M&M", pChange: 4 },
  { symbol: "MARUTI", pChange: 8.5 },
  { symbol: "NESTLEIND", pChange: 5 },
  { symbol: "NTPC", pChange: 2 },
  { symbol: "ONGC", pChange: 2.5 },
  { symbol: "POWERGRID", pChange: 2 },
  { symbol: "RELIANCE", pChange: 4 },
  { symbol: "SBILIFE", pChange: 2 },
  { symbol: "SBIN", pChange: 3 },
  { symbol: "SUNPHARMA", pChange: 4 },
  { symbol: "TATACONSUM", pChange: 3 },
  { symbol: "TATAMOTORS", pChange: 3 },
  { symbol: "TATASTEEL", pChange: 2.5 },
  { symbol: "TCS", pChange: 4 },
  { symbol: "TECHM", pChange: 2 },
  { symbol: "TITAN", pChange: 4.5 },
  { symbol: "ULTRACEMCO", pChange: 8.5 },
  { symbol: "SHRIRAMFIN", pChange: 5 },
  { symbol: "WIPRO", pChange: 2.5 }
];

// Use this stockData in your component where you were using `stocks`

export default stockData;
